### ISSUE TITLE
Not working with EAS Updates on iOS

### ISSUE THREAD

**Issue by grgmgd** [ivopr/tamagui-expo#10]
Submitting an EAS update on a freshly initialized project results in the following error: 

![image](https://user-images.githubusercontent.com/25729498/199773568-011a8177-1a68-44a7-9de9-12d1e28744c2.png)

Working on Android fine though, any ideas what might be causing the issue?

**Comment by ivopr** [comment]
@grgmgd well, now we have a problem. never faces this error before and I don't have a iOS device to test on. could you try disabling Hermes? It's on `app.json`, Just remove the `jsEngine` line

**Comment by flexbox** [comment]
Hey @grgmgd 

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by ivopr** [comment]
Hey @grgmgd, with Expo 47 came support for Hermes in Expo Go for iOS, this repo is on Expo 47 already, so things should go nicely now.
