### ISSUE TITLE
File 'expo/tsconfig.base' not found

### ISSUE THREAD

**Issue by jkohlin** [ivopr/tamagui-expo#12]
Hi. I just installed tamagui by following the instructions in the readme but got this error in the tsconfig.json.
I'm new to typescript and not sure what to do.
Any help?

**Comment by ivopr** [comment]
@jkohlin hey, you probably need to run `yarn install`, this file is included on the `expo` package, If you already ran `yarn install` try reopening the project in your ide

**Comment by jkohlin** [comment]
Well, I started by running `npx create-expo-app sni -t tamagui-expo-template --no-install` followed by `cd sni` and `yarn install`.
the error above was fixed by adding .json to ` "extends": "expo/tsconfig.base"` but
When I run `yarn start` I get this:
```
Some dependencies are incompatible with the installed expo version:
  expo-dev-client@2.0.0 - expected version: ~2.0.1
  react@18.2.0 - expected version: 18.1.0
  react-dom@18.2.0 - expected version: 18.1.0
  react-native-reanimated@2.13.0 - expected version: ~2.12.0
Your project may not work correctly until you install the correct versions of the packages.
```
and my screen shows this:
![image](https://user-images.githubusercontent.com/4112881/208548527-b35a70b4-dcc1-4c3f-bb13-ff9fb95ab481.png)
so I try running `expo-cli doctor --fix-dependencies`
but still the same error.
Any clues?

**Comment by ivopr** [comment]
try adding
```
"resolutions": {
"react": "18.2.0",
"react-dom": "18.2.0
}
```
to your package json, tamagui needs React 18.2, and running expo doctor enforces 18.1

**Comment by jkohlin** [comment]
that worked! thanks.
Now it's just a warning: ` warning: matchMedia implementation is not provided.`
![image](https://user-images.githubusercontent.com/4112881/208551790-79482f40-3ea2-41bb-8c50-5e8fd0d4f729.png)

**Comment by ivopr** [comment]
you can ignore this for now.
not sure why it is happening, will try to find next week when vacation starts

**Comment by ivopr** [comment]
forgot to mention in the commit, but added the `.json` to it. If needed, please reopen.
