### ISSUE TITLE
compiling for iOS 12.0, but module 'ExpoModulesCore' has a minimum deployment target of iOS 13.0

### ISSUE THREAD

**Issue by flexbox** [ivopr/tamagui-expo#13]
Hey, thanks for this repo 🙌

I tried on my machine and encountered the famous "error code 65"

<img width="912" alt="image" src="https://user-images.githubusercontent.com/360936/210074213-7f10526c-5bf5-4358-98c9-5cad4e6d6438.png">

**To Reproduce**
1. `npx create-expo-app youprojectname -t tamagui-expo-template --no-install`
2. `yarn`
3. `yarn ios`

```
› Packaging expo-application Pods/EXApplication » libEXApplication.a
› Compiling expo-font Pods/EXFont » EXFontScaler.m
› Compiling expo-font Pods/EXFont » EXFontManager.m

❌  (node_modules/expo-screen-orientation/ios/EXScreenOrientation/ScreenOrientationAppDelegate.swift:3:8)

  1 | // Copyright 2018-present 650 Industries. All rights reserved.
  2 |
> 3 | import ExpoModulesCore
    |        ^ compiling for iOS 12.0, but module 'ExpoModulesCore' has a minimum deployment target of iOS 13.0: /Users/cerebra/Library/Developer/Xcode/DerivedData/Tamagui10-frkvdjtacrpuwoddynjaccsqwqfw/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule/arm64-apple-ios-simulator.swiftmodule
  4 |
  5 | public class ScreenOrientationAppDelegate: ExpoAppDelegateSubscriber {
  6 |   public func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
```

```console
sw_vers && /usr/bin/xcodebuild -version
```
```
ProductName:		macOS
ProductVersion:		13.0.1
Xcode                             14.2
```

### Expo doctor 

```console
expo-cli doctor
```
```console
🎉 Didn't find any issues with the project!
```

**Comment by ivopr** [comment]
well, my only guess is that the version of `expo-screen-orientation` may be outdated. could you try running `expo upgrade` to ensure things are updated?
also, I'm not familiar with RN on iOS/Mac, are pods installed automatically?

**Comment by flexbox** [comment]
> are pods installed automatically?

yes 

![image](https://user-images.githubusercontent.com/360936/210092360-c89f74d9-67e3-46d6-85ae-ac8466946cfd.png)

Same error after running
```
expo-cli upgrade
```

![image](https://user-images.githubusercontent.com/360936/210092728-a6d63f93-3d84-4eac-b651-19bcb620adc4.png)

I tried to run 
```
yarn add expo-screen-orientation
```

it solves the build issue 🎉

but we still have #12 😅

**Comment by ivopr** [comment]
@flexbox that's great! I'll add the lib and check #12.
