### ISSUE TITLE
Setting up repo gives error

### ISSUE THREAD

**Issue by rohanprasadofficial** [ivopr/tamagui-expo#15]
I cloned this template and did : 
`yarn install`
`yarn android`

The app installs and while running & loading the bundle it is giving error : 

<img width="794" alt="Screenshot 2023-01-08 at 9 13 13 PM" src="https://user-images.githubusercontent.com/30728574/211205859-b18f72a5-5e8c-4d81-af2e-267d14ed4319.png">

**Comment by ivopr** [comment]
@rohanprasadofficial please make sure that `react` is de-duped.
try setting `react` on resolutions to 18.2

**Comment by rohanprasadofficial** [comment]
@ivopr , it worked, thanks really appreciate the support.

**Comment by rohanprasadofficial** [comment]
@ivopr , it worked, thanks really appreciate the support.
