### ISSUE TITLE
Upgrade Tamagui version

### ISSUE THREAD

**Issue by oreoluwa-bs** [ivopr/tamagui-expo#18]
A render error occurs with the Tamagui packages 1.0.1 when using the `<Input />` component.
![simulator_screenshot_85891790-0236-4E1A-A35B-600870F026C8](https://user-images.githubusercontent.com/46888096/213489094-42ee7eb3-9e5c-4c4c-bb23-7f23476b3f12.png)

Possible fix:
Upgrade Tamagui version to latest / 1.0.13
<img width="396" alt="Screenshot 2023-01-19 at 16 46 55" src="https://user-images.githubusercontent.com/46888096/213488024-8dfb008c-3c53-4cfd-8de3-d6216bc7d104.png">

The cause is the `stepTokenUpOrDown` function is being imported from the wrong module.

**Comment by ivopr** [comment]
@oreoluwa-bs thanks, I didn't even test it before. Did the upgrade and this time tested it.
