### ISSUE TITLE
Failed prop type: Invalid props.style key `cursor` supplied to `Text`

### ISSUE THREAD

**Issue by ogmzh** [ivopr/tamagui-expo#20]
Hi there, I cloned your tamagui demo and am getting the following error from the title. Attached a screenshot also. Got an idea what I might've done wrong building the app since cursor in react-native css is an invalid prop?
![image](https://user-images.githubusercontent.com/12704199/226573045-0f77d9c2-5fe4-429a-8915-e8eeaef1a6bc.png)

**Comment by ivopr** [comment]
Hey there @zhGio, that's exactly it. there's a set of style keys that won't work and will either not be implemented (such as cursor, i think) and others that eventually make it through (like flexGap, that came with RN 0.71 if I'm not wrong).

**Comment by ogmzh** [comment]
But how do i handle this error or prevent it from popping up all the time? Bear in mind I just cloned your repo and ran it :smile:

**Comment by ivopr** [comment]
@zhGio as React Native doesn't support cursors, just don't use it (cursor prop). If your app is for mobile and web, as mentioned in the readme, probably your best choice would be the official tamagui starter

**Comment by ogmzh** [comment]
Turns out this was some mess on my WSL running multiple expo apps and cleaning expo cache and rebuilding the tamagui solved it :)
