### ISSUE TITLE
Errors in a clean repo

### ISSUE THREAD

**Issue by tjapa** [ivopr/tamagui-expo#21]
I started a new repo with this template and I'm getting some errors:

![image](https://user-images.githubusercontent.com/17579637/228362298-b8fab10b-7c30-41f9-a0b0-6ca4bee88c17.png)
![image](https://user-images.githubusercontent.com/17579637/228362331-9313acdb-f507-4290-8400-18561383b393.png)
![image](https://user-images.githubusercontent.com/17579637/228362439-7f9a1d08-4215-4c66-ad83-bdcf749b202d.png)

I tried with Node V16 and V18.

**Comment by tjapa** [comment]
My fault, sorry. I forget to set the env variable to web.

**Comment by ichi0g0y** [comment]
This problem remains. Are there any plans to fix it in the future?
