### ISSUE TITLE
Cannot find native module 'Burnt' error

### ISSUE THREAD

**Issue by kalvinwang** [ivopr/tamagui-expo#24]
After running yarn start on a fresh repo, when I navigate to a user page in Expo Go on iOS and tap "Show Toast", I get the following error:

```Logs for your project will appear below. Press Ctrl+C to exit.
iOS Bundling complete 2471ms
 ERROR  Error: Cannot find native module 'Burnt', js engine: hermes
 ERROR  TypeError: Cannot read property 'toast' of undefined, js engine: hermes
```

Is this expected because it's Expo Go and a native module (no, I think?), or how can I fix this? I'm new to Expo and Tamagui. Thank you!

**Comment by ivopr** [comment]
@kalvinwang As per [Burnt's installation guide](https://github.com/nandorojo/burnt#installation) it doesn't support Expo Go (yep, just found out about it too), it indeed is what you said, a native module that must be built into the client, which is strange as it just works on Expo Go on my Android device. Guess I'll be removing the toast example for now. Thanks.
