### ISSUE TITLE
Does not work on web `npx expo start -w` or `npm run web`

### ISSUE THREAD

**Issue by siarheipashkevich** [ivopr/tamagui-expo#27]
![image](https://github.com/ivopr/tamagui-expo/assets/7753600/c03d7848-c4eb-4ba4-851d-ddc4bc57f1a7)

**Comment by ivopr** [comment]
that's also expected, on the readme I mentioned that this project isn't setup for expo web. If you need mobile and web on the same project, you should probably use the oficial tamagui starter.

**Comment by siarheipashkevich** [comment]
Do you plan to support `web` ?

**Comment by ivopr** [comment]
nope, If I remember right, there was some lib that was blocking this in the past. but as I said, If you need web+mobile in the same codebase you should probably Go to the oficial tamagui starter

**Comment by siarheipashkevich** [comment]
got it, thanks
