### ISSUE TITLE
How to use environment variables using `.env`?

### ISSUE THREAD

**Issue by siarheipashkevich** [ivopr/tamagui-expo#29]
Is it possible to use environment variables using `.env` file and using `eas` ?

**Comment by ivopr** [comment]
There's been some time since I did anything with RN (this repo os the one I fiddle the most about RN these days), but for .env file tou could use react-native-dotenv, and on eas there is a place on the UI to add Secrets, where tou can put the contents of your .env file

**Comment by ivopr** [comment]
hey @siarheipashkevich I'll be closing this since it's more of how to use the Expo/RN framework instead of some kind of error or whatnot in this repo
