### ISSUE TITLE
How to turn off semicolons in the template

### ISSUE THREAD

**Issue by nikivdev** [ivopr/tamagui-expo#31]
Thank you for making the template. 

I have project that builds on it here: https://github.com/kuskusapp/mobile

However I don't get how to turn off semicolons. I made the prettier config to use `semi: false`. However it is still being added by ESLint. However if I do this:

<img width="973" alt="image" src="https://github.com/ivopr/tamagui-expo/assets/6391776/e7f9c446-9abd-493d-8a1d-05dbd633560c">

I get these errors:

<img width="1262" alt="image" src="https://github.com/ivopr/tamagui-expo/assets/6391776/b2562683-7ba2-4216-84d5-f3386a3ccf58">

Not sure how I can solve them.

**Comment by ivopr** [comment]
setting `semi` to false in `.prettierrc` worked here. Try setting it and reloading your VSCode

**Comment by nikivdev** [comment]
Thank you, that did work
