### ISSUE TITLE
How would you do env variables?

### ISSUE THREAD

**Issue by nikivdev** [ivopr/tamagui-expo#34]
This is my first react native project and I am struggling to import env vars.

I cannot do this

<img width="895" alt="image" src="https://github.com/ivopr/tamagui-expo/assets/6391776/60dc1b7b-7a04-4dbf-941f-3dde23ca87a3">

I tried adding secret to EAS but its unclear what to do with it after

<img width="374" alt="image" src="https://github.com/ivopr/tamagui-expo/assets/6391776/39afa40e-813c-4ef4-99b3-cdcc4529d3f1">

Found [this video](https://www.youtube.com/watch?v=S_FxR061rrA) that says you should use [react-native-dotenv](https://www.npmjs.com/package/react-native-dotenv). Trying it out now but I do wonder what's the recommended by this template way to use env variables?

Thank you.

**Comment by ivopr** [comment]
I would do react-native-dotenv, it's the recommended way to do this by the community.

**Comment by michaeljamieson10** [comment]
that you can access using expo constants and treat it like env variables instead of using env, I got rid of process.env all together. if you really need process.env you will have to use app.config.js

**Comment by ivopr** [comment]
well, I'll be closing this, as apparently a solution was found in another issue. I'm also sorry for neglecting this as I didn't had time to be active until recently.
