### ISSUE TITLE
SafeAreaView doesn't play nice with dark mode

### ISSUE THREAD

**Issue by jackbcodes** [ivopr/tamagui-expo#36]
Thanks for this repo! Just trying it out and SafeAreaView stays white when you enter dark mode.

I added this in my code, would you be open to a PR?

```
  const SafeAreaView = styled(DefaultSafeAreaView, {
    backgroundColor: "$backgroundStrong",
    flex: 1
  });

  return (
    <TamaguiProvider config={config}>
      <Suspense fallback={<Text>Loading...</Text>}>
        <Theme name={colorScheme}>
          <ThemeProvider
            value={colorScheme === "light" ? DefaultTheme : DarkTheme}
          >
            <SafeAreaView>
              <Stack
                screenOptions={{
                  headerShown: false
                }}
              />
            </SafeAreaView>
          </ThemeProvider>
        </Theme>
      </Suspense>
    </TamaguiProvider>
  );
  ```

**Comment by ivopr** [comment]
Hey there, thanks. If you could open a PR I would be delighted to check it out and merge

**Comment by jackbcodes** [comment]
Cool, PR 👉 #37

**Comment by ivopr** [comment]
I've merged the PR and forgot to close the issue, my bad hehe

**Comment by jackbcodes** [comment]
Haha, I've got another suggestion if you're open to it?

I've added "@/" as an alias, which is quite common in Next and Remix templates now. I could open a PR for that?

E.g.

`import { MyStack } from "@/components/MyStack"`

**Comment by ivopr** [comment]
@jackbcodes feel free to keep 'em coming. I don't have as much time as before but I'll do my best to Review and merge them
