### ISSUE TITLE
Fast refresh not working

### ISSUE THREAD

**Issue by randomGitBeing132** [ivopr/tamagui-expo#43]
After cloning the starter and running yarn install, everytime after saving code changes it does not hot reload on android/ios emulators or physical devices.

I also checked that "Fast refresh" is enabled on all the devices through dev menu.

**Comment by ivopr** [comment]
well, that's strange, for me it is refreshing, it just don't give me the alert as it did with expo 48.

could you try with `npx create-expo-app yourappname -t tamagui-expo-template@3.2.6 --no-install` and check if it works?

**Comment by ivopr** [comment]
well, @randomGitBeing132 I'll close this as there's no response, feel free to reopen if needed
