### ISSUE TITLE
Tabs changes are very slow.

### ISSUE THREAD

**Issue by BrijenMakwana** [ivopr/tamagui-expo#46]
I'm using tabs in my app. When I change between tabs, it takes 1-2 s to actually change the tabs.

**Comment by ivopr** [comment]
@BrijenMakwana did you update the dependencies? it's already some time since I last did It, also, be aware that React Native *Will* Mount all screen components at once, so the slowness is to be expected If tour screen is too heavy. Well, I don't really know what you did, but per your description It doesn't seem like it is an issue in the template. Feel free to reopen with more details If needed

**Comment by BrijenMakwana** [comment]
I'm using all the latest versions for dependencies. I'm not even providing any components to render in the tabs. Still it changes very slowly.

**Comment by ivopr** [comment]
well, let me reopen, I'll try It when I get home later

**Comment by ivopr** [comment]
hey @BrijenMakwana first off I'm really sorry about the time it took me to check on this again. Not gonna lie, I completely forgot. I've updated Tamagui to the latest, at least with 2 empty tabs, on dev environment it seems pretty fast to me (on click change), could you try it?

**Comment by BrijenMakwana** [comment]
By tabs, I didn't mean expo router tabs. There couldn't be any problem with it. I meant tabs from tamagui. It's an expo template for tamagui, that's why raised the issue.

**Comment by ivopr** [comment]
oh, I've thought for sure It was about router tabs, well happens, I'll check It out

**Comment by ivopr** [comment]
hey again @BrijenMakwana, just tested and added an example of it to the template, and it is fast here. Could you check it out now?

**Comment by BrijenMakwana** [comment]
It's the same. It is lagging. It doesn't happen instantly. But I guess there's nothing wrong here. I just checked that tabs in tamagui is still in beta. Maybe it'll improve in the future. You can close this issue. Thank you for your efforts.

**Comment by ivopr** [comment]
then I'll be closing it, I'll keep an eye open about this too.
