### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by konyilwin** [ivopr/tamagui-expo#6]
![307432417_461061772453135_5392718658284161514_n](https://user-images.githubusercontent.com/30022185/191771336-64c8c0a1-f28a-4d74-8537-49aef5a4bcec.jpg)

**Comment by ivopr** [comment]
You're supposed to use [Expo Dev Client](https://docs.expo.dev/development/getting-started/#creating-and-installing-your-first-development-build), as there is some native code that Expo Go doesn't have.
For the next week I'll be trying to make it work on Expo Go, but support for MMKV (that provides persistence), MobX (Global State Management) and I18n will be dropped.

sorry for the delay, I've been quite away from things lately

**Comment by ivopr** [comment]
@konyilwin Expo Go support landed, just note that things like persistence, i18n and Global State Management were dropped to achieve this, and if you need it or anything that involve native code can only be achieved by building your very own Expo Dev Client.

**Comment by konyilwin** [comment]
> 

thank you so much

**Comment by ivopr** [comment]
Well, we might need to wait a bit more, just noted that GH Actions aren't running...

edit: it started as I hit 'reopen' (I reopened to remember to trigger the action later)
edit2: now it is published on npm properly
