### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by GigaBigBoss** [ivopr/tamagui-expo#8]
![image](https://user-images.githubusercontent.com/106954969/194675383-7446bb43-4a92-4072-808c-cb7f32044ab7.png)

**Comment by ivopr** [comment]
[Expo](https://expo.dev) is a framework built using [React Native](https://reactnative.dev) which is a mobile app framework, it supports Android, iOS and Web. This template isn't ready for Web, nor do I want it to be, as I make my web projects with [Nextjs](https://nextjs.org) and [Vite](https://vitejs.dev). If you want to make use of Web with this template you'll probably need proper configuring with `Webpack` and as your screenshot says, an appropriate loader to parse the code to run on browser. At this point, if you really need Web support I recommend you to use the official [Tamagui Starter](https://tamagui.dev/docs/guides/create-tamagui-app), which comes configured with code sharing, a web app with Nextjs and a mobile app with Expo. I suppose that this also is valid for your other issue (#9)
